# render.yaml - Single Production Environment

databases:
  - name: ai-finance-dashboard-db
    databaseName: finance_dashboard
    user: finance_user
    plan: starter # Production-ready plan

services:
  # Backend API Service
  - type: web
    name: ai-finance-dashboard-backend
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/yourusername/finance-dashboard.git
    branch: main
    rootDir: backend
    buildCommand: npm run render:build
    startCommand: npm run render:start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ai-finance-dashboard-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false # Set manually in Render dashboard
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://ai-finance-dashboard-frontend.onrender.com

  # Frontend Web Service
  - type: web
    name: ai-finance-dashboard-frontend
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/yourusername/finance-dashboard.git
    branch: main
    rootDir: frontend
    buildCommand: npm run render:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-finance-dashboard-backend.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://ai-finance-dashboard-backend.onrender.com
      - key: NEXT_PUBLIC_APP_NAME
        value: AI Finance Dashboard
      - key: SKIP_LINT
        value: true
